projects:
  app:
    schemaPath: "src/schema.graphql"
    includes: ["queries/{booking,queries}.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:5000"
  database:
    schemaPath: "src/generated/database.graphql"
    includes: ["database/seed.graphql"]
    extensions:
      graphcool: database/graphcool.yml
      prepare-binding:
        output: src/generated/graphcool.ts
        generator: graphcool-ts
